---
root: true

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

parser: babel-eslint

env:
  browser: true
  node: true
  jest: true

rules:
  no-console: 0
  import/extensions: 0
  comma-dangle: 0
  implicit-arrow-linebreak: 0
  function-paren-newline: 0
  new-cap:
    - error
    - properties: false
  no-param-reassign:
    - error
    - props: true
      ignorePropertyModificationsFor:
        - req
        - reply
